-- apply changes
create table genres (
  id                            integer generated by default as identity not null,
  order_number                  integer not null,
  created_at                    timestamptz not null,
  updated_at                    timestamptz not null,
  name                          varchar(10),
  key                           varchar,
  image_path                    varchar,
  image_key                     varchar,
  constraint pk_genres primary key (id)
);

create table dmember (
  id                            integer generated by default as identity not null,
  sex                           integer,
  created_at                    timestamptz not null,
  updated_at                    timestamptz not null,
  name                          varchar(10),
  constraint pk_dmember primary key (id)
);

create table dphone (
  id                            integer generated by default as identity not null,
  member_id                     integer,
  is_home_phone_no              boolean default false not null,
  created_at                    timestamptz not null,
  updated_at                    timestamptz not null,
  phone_no                      varchar,
  constraint pk_dphone primary key (id)
);

-- foreign keys and indices
create index ix_dphone_member_id on dphone (member_id);
alter table dphone add constraint fk_dphone_member_id foreign key (member_id) references dmember (id) on delete restrict on update restrict;

