datasource.default = rapit

datasource.rapit.username = ${DB_USER_NAME:postgres}
datasource.rapit.password = ${DB_PASSWORD:postgres}
datasource.rapit.url = jdbc:postgresql://${DB_HOST_NAME:localhost}:5432/${DB_NAME:rapit}
datasource.rapit.driver = org.postgresql.Driver

datasource.rapit.minConnections = 1
datasource.rapit.maxConnections = 5
datasource.rapit.maxIdleTimeInSeconds = 60
datasource.rapit.waitTimeoutMillis = 1000
datasource.rapit.heartbeatSql = select 1

ebean.dbSchema = public
ebean.migration.run = true